### ISSUE TITLE
Question about prompt gen

### ISSUE THREAD

**Issue by pixeli99** [KyanChen/RSPrompter#4]
Very interesting work！！！

I have a question to ask, why do you need to directly generate the 256 dimensional vector corresponding to the point prompt when designing a network instead of predicting k coordinate points?

**Comment by KyanChen** [comment]
Considering that generating point coordinates requires searching in the original SAM prompt’s manifold, which greatly limits the optimization space of the prompter, we further relax the representation of prompts and directly generate prompt embeddings, which can be understood as the embeddings of points or boxes, instead of the original coordinates. This design also avoids the obstacle of gradient flow from high-dimensional to low-dimensional and then back to high-dimensional features, i.e., from high-dimension image features to point coordinates and then to positional encodings.
