### ISSUE TITLE
no pos rois

### ISSUE THREAD

**Issue by xyLpf** [KyanChen/RSPrompter#92]
麻烦大佬看下，我用的配置文件是rsprompter_anchor-whu.py，数据集是自己整理的coco格式的实例分割数据集，在训练时会出现no pos rois。是什么问题？
![rs_error](https://github.com/KyanChen/RSPrompter/assets/49382098/a80a0dc9-1fc8-4117-9e9b-3a859e9d4012)

数据格式：
![image](https://github.com/KyanChen/RSPrompter/assets/49382098/1882a0c3-ab1a-47d3-97f5-fde38ddff1d6)

**Comment by pengyuting181** [comment]
同问

**Comment by pengyuting181** [comment]
maybe the coco class is at fault in coco.py

**Comment by funny000** [comment]
@xyLpf，你发现这个问题出在哪里了吗

**Comment by AImagicAI** [comment]
同样的问题，请问您解决了吗？如何解决的呢？

**Comment by AImagicAI** [comment]
同样的问题，请问您解决了吗？如何解决的呢？

**Comment by KyanChen** [comment]
估计是训练样本存在空的标注

**Comment by AImagicAI** [comment]
您好，我查看了所有标签，没有空标注？请问您是怎么排查的呢？谢谢！



---Original---
From: "Keyan ***@***.***&gt;
Date: Fri, Mar 29, 2024 16:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [KyanChen/RSPrompter] no pos rois (Issue #92)




 
估计是训练样本存在空的标注

**Comment by wwlaoxi** [comment]
我用whu数据集训练正常，但是用自己的数据集训练也出现了no pos rois，怎么解决呢？

**Comment by wwlaoxi** [comment]
我用whu数据集训练正常，但是用自己的数据集训练也出现了no pos rois，怎么解决呢？

**Comment by gzixiao** [comment]
请问问题解决了吗，我也遇到了这个问题

**Comment by funny000** [comment]
可能是数据问题，现在已经不用这个模型了


2152550864
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KyanChen/RSPrompter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年2月22日(星期六) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KyanChen/RSPrompter] no pos rois (Issue #92)



   
请问问题解决了吗，我也遇到了这个问题

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  Oriongzx left a comment (KyanChen/RSPrompter#92)
 
请问问题解决了吗，我也遇到了这个问题
